import type { CSSProperties } from 'react'

type Styles = Record<string, CSSProperties>

export const s: Styles = {
  app: {
    minHeight: '100vh',
    backgroundColor: '#0a0a0a',
    color: '#e5e5e5',
    fontFamily: "ui-monospace, 'SF Mono', Menlo, Monaco, Consolas, monospace",
    maxWidth: 480,
    margin: '0 auto',
    paddingBottom: 40,
  },
  loading: {
    minHeight: '100vh',
    backgroundColor: '#0a0a0a',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navBar: {
    display: 'flex',
    borderBottom: '1px solid #1f1f1f',
    position: 'sticky',
    top: 0,
    backgroundColor: '#0a0a0a',
    zIndex: 10,
  },
  navBtn: {
    flex: 1,
    padding: '14px 0',
    backgroundColor: 'transparent',
    border: 'none',
    fontSize: 11,
    fontFamily: 'inherit',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    cursor: 'pointer',
  },
  content: {
    padding: 16,
  },
  dateHeader: {
    marginBottom: 14,
  },
  dateMain: {
    fontSize: 20,
    fontWeight: 600,
    letterSpacing: '-0.02em',
  },
  dateSub: {
    fontSize: 11,
    color: '#666',
    marginTop: 2,
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
  },
  card: {
    backgroundColor: '#111',
    border: '1px solid #1f1f1f',
    borderRadius: 4,
    padding: 14,
  },
  cardLabel: {
    fontSize: 10,
    color: '#666',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    marginBottom: 8,
  },
  sectionLabel: {
    fontSize: 10,
    color: '#666',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    marginBottom: 8,
  },
  bigNumber: {
    fontSize: 32,
    fontWeight: 700,
    lineHeight: 1,
    fontVariantNumeric: 'tabular-nums',
    display: 'flex',
    alignItems: 'baseline',
    gap: 6,
  },
  unit: {
    fontSize: 13,
    color: '#666',
    fontWeight: 400,
  },
  progressBg: {
    height: 4,
    backgroundColor: '#1a1a1a',
    borderRadius: 2,
    overflow: 'hidden',
    marginTop: 10,
  },
  progressFill: {
    height: '100%',
    transition: 'width 0.3s ease',
  },
  statsRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginTop: 8,
    fontSize: 12,
  },
  statNum: {
    color: '#e5e5e5',
    fontVariantNumeric: 'tabular-nums',
  },
  statLabel: {
    color: '#666',
  },
  noteBadge: {
    marginTop: 10,
    fontSize: 11,
    color: '#d4b85a',
    padding: '4px 8px',
    backgroundColor: '#1a1a0e',
    borderRadius: 3,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
  },
  proteinRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  proteinBig: {
    fontSize: 22,
    fontWeight: 700,
    color: '#6a9ad4',
    fontVariantNumeric: 'tabular-nums',
  },
  proteinUnit: {
    fontSize: 12,
    color: '#666',
    fontWeight: 400,
  },
  mealRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 0',
    borderBottom: '1px solid #1a1a1a',
  },
  mealKcal: {
    fontSize: 13,
    color: '#e5e5e5',
    fontWeight: 600,
    marginRight: 10,
    fontVariantNumeric: 'tabular-nums',
  },
  mealProtein: {
    fontSize: 11,
    color: '#6a9ad4',
    fontVariantNumeric: 'tabular-nums',
  },
  iconBtn: {
    background: 'transparent',
    border: 'none',
    color: '#555',
    cursor: 'pointer',
    padding: 4,
    display: 'flex',
  },
  addBtn: {
    width: '100%',
    padding: 12,
    marginTop: 12,
    backgroundColor: 'transparent',
    border: '1px dashed #333',
    borderRadius: 4,
    color: '#888',
    fontSize: 13,
    fontFamily: 'inherit',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryBtn: {
    flex: 1,
    padding: 11,
    backgroundColor: '#d4b85a',
    color: '#0a0a0a',
    border: 'none',
    borderRadius: 3,
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'inherit',
    cursor: 'pointer',
    letterSpacing: '0.03em',
  },
  secondaryBtn: {
    flex: 1,
    padding: 11,
    backgroundColor: '#1f1f1f',
    color: '#e5e5e5',
    border: 'none',
    borderRadius: 3,
    fontSize: 13,
    fontFamily: 'inherit',
    cursor: 'pointer',
  },
  ghostBtn: {
    padding: '11px 16px',
    backgroundColor: 'transparent',
    color: '#888',
    border: '1px solid #2a2a2a',
    borderRadius: 3,
    fontSize: 13,
    fontFamily: 'inherit',
    cursor: 'pointer',
  },
  actionBtn: {
    padding: 11,
    backgroundColor: '#111',
    border: '1px solid #2a2a2a',
    borderRadius: 4,
    color: '#e5e5e5',
    fontSize: 12,
    fontFamily: 'inherit',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  input: {
    width: '100%',
    padding: 10,
    backgroundColor: '#0a0a0a',
    border: '1px solid #2a2a2a',
    borderRadius: 3,
    color: '#e5e5e5',
    fontFamily: 'inherit',
    fontSize: 14,
    marginTop: 4,
    marginBottom: 8,
    boxSizing: 'border-box',
    colorScheme: 'dark',
  },
  inputLabel: {
    fontSize: 10,
    color: '#666',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    display: 'block',
    marginTop: 4,
  },
  weekHeader: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: 2,
    marginBottom: 2,
  },
  weekHeaderCell: {
    textAlign: 'center',
    fontSize: 9,
    color: '#555',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    padding: '4px 0',
  },
  weekRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: 2,
    marginBottom: 2,
  },
  dayCell: {
    aspectRatio: '1',
    backgroundColor: 'transparent',
    border: '1px solid transparent',
    borderRadius: 3,
    position: 'relative',
  },
  dayCellBtn: {
    cursor: 'pointer',
    fontFamily: 'inherit',
    color: '#888',
    padding: 0,
    border: '1px solid #1a1a1a',
    backgroundColor: '#0f0f0f',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayCellSelected: {
    border: '1px solid #d4b85a',
    backgroundColor: '#1a1a0e',
    color: '#d4b85a',
  },
  dayCellToday: {
    fontWeight: 700,
    color: '#e5e5e5',
  },
  dayNum: {
    fontSize: 12,
    lineHeight: 1,
    fontVariantNumeric: 'tabular-nums',
  },
  dayDots: {
    display: 'flex',
    gap: 2,
    marginTop: 3,
    height: 4,
    alignItems: 'center',
  },
  dot: {
    width: 3,
    height: 3,
    borderRadius: '50%',
    display: 'inline-block',
  },
  breakdownRow: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '4px 0',
    fontSize: 12,
  },
  breakdownLabel: {
    color: '#888',
  },
  breakdownVal: {
    fontVariantNumeric: 'tabular-nums',
    color: '#e5e5e5',
  },
  modalBg: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    zIndex: 100,
  },
  modal: {
    backgroundColor: '#111',
    border: '1px solid #2a2a2a',
    borderRadius: 6,
    padding: 20,
    width: '100%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: 600,
    marginBottom: 14,
    color: '#d4b85a',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
  },
  toggleBtn: {
    padding: '8px 4px',
    backgroundColor: '#0a0a0a',
    border: '1px solid #2a2a2a',
    borderRadius: 3,
    color: '#888',
    fontSize: 11,
    fontFamily: 'inherit',
    cursor: 'pointer',
    textAlign: 'center',
  },
  toggleBtnActive: {
    backgroundColor: '#1a1a0e',
    border: '1px solid #d4b85a',
    color: '#d4b85a',
  },
}
